#!/bin/bash
# ask tools git-credential-helper

source ~/.ask/auth_info

profile=$1
skillId=$2
configFile=~/.ask/cli_config
if [ -f "${configFile}" ]; then
    configOp="s/.*\"${profile}\":{[^{]*\"token\":{[^{]*\"refresh_token\":\"\([^{]*\)\"/\1/p"
    askRefreshToken=$(tr -d '\n' <  "${configFile}" | tr -d ' ' | sed -n "${configOp}" | sed 's/".*//')
fi

refreshToken="${ASK_REFRESH_TOKEN:-$askRefreshToken}"
lwaAPI="${ASK_LWA_TOKEN_HOST:-$ask_lwa_api}"
smapiAPI="${ASK_SMAPI_SERVER_BASE_URL:-$ask_smapi_api}"
clientID="${ASK_LWA_CLIENT_ID:-$ask_client_id}"
clientSecret="${ASK_LWA_CLIENT_CONFIRMATION:-$ask_client_confirmation}"

token=$(curl -f -s -d grant_type=refresh_token -d client_id="${clientID}" -d client_secret="${clientSecret}" -d refresh_token="${refreshToken}" \
 "${lwaAPI}"/auth/O2/token)
accessToken=$(tr -d '\n'  <<< "${token}" | tr -d ' ' | sed 's/.*"access_token":"\([^{]*\)","refresh_token".*/\1/') 
if [[ -z "${accessToken}" ]]; then
    echo "Failed to fetch a LWA access token."
    exit 1
fi

alexaHosted=$(curl -f -s -H "Authorization: Bearer ${accessToken}" "${smapiAPI}"/v1/skills/"${skillId}"/alexaHosted)
url=$(tr -d '\n'  <<< "${alexaHosted}" | tr -d ' ' | sed -n 's/.*"url":"\([^{]*\)"},"runtime".*/\1/p')
type=$(tr -d '\n'  <<< "${alexaHosted}" | tr -d ' ' | sed -n 's/.*"type":"\([^{]*\)","url".*/\1/p')
if [[ ( -z "${url}" ) || ( -z "${type}" ) ]]; then
    echo "The Alexa-hosted skill is not found with id: ${skillId}."
    exit 1
fi

repoJson='{"repository":{"type":"'"${type}"'","url":"'"${url}"'"}}'
credential=$(curl -f -s -H "Authorization: Bearer ${accessToken}" -d "${repoJson}" \
 "${smapiAPI}"/v1/skills/"${skillId}"/alexaHosted/repository/credentials/generate)
password=$(sed -n 's/.*password":"\(.*\)".*/\1/p' <<< "${credential}" | sed 's/".*//')
username=$(sed -n 's/.*username":"\(.*\)".*/\1/p' <<< "${credential}" | sed 's/".*//')
if [[ (-z "${password}") || (-z "${username}") ]]; then
    echo "Failed to generate repository credentials for the Alexa-hosted skill with id: ${skillId}."
    exit 1
fi
echo "username=${username}"
echo "password=${password}"
